name: CI

on: [push]

jobs:
  publishMasterCommit:
    name: Publish to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Save Gatsby .cache
        uses: actions/cache@v2
        with:
          path: |
            /.cache
            /node_modules
          key: ${{ runner.os }}
      - name: build
        run: |
          yarn install
          yarn add netlify-cli
          make build
      - name: Publish
        run: make deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
